### ISSUE TITLE
Thing don't work

### ISSUE THREAD

**Issue by Ondaedj** [ContentCreatorsSuite/Nobot-public#1]
**Describe the bug**
Bug is a bunch of BS that breaks everything.  Pisses me off.
(Literally crashes the bot and stops all functionality.)

**To Reproduce**
1. Go to 'Stream?'
2. Click on 'Chat area'
3. Scroll down to 'No'
3.1 Type '!quote -(number that doesn't exists as a quote)'
4. This is the end, my friend

**Expected behavior**
Nothing really, but it continues to do nothing beyond the point that I would expect it to start doing things again.

**Screenshots**
Um... no

**Additional context**
Pawn said during stream to report it here.  
"It ain't my problem, take your complaints to the door (Then walk them over to Noah at the following address)" 
(Actual Pawn quote may vary, I can't be expected to remember every damned thing)

**Comment by noahkra** [comment]
Not really the best bug report I've ever seen... but should be an easy fix.

**Comment by noahkra** [comment]
Fixed.
