### ISSUE TITLE
Twitch feedback command broke

### ISSUE THREAD

**Issue by Leytra** [ContentCreatorsSuite/Nobot-public#3]
**Describe the bug**
The twitch feedback thing doesn't fuckin work

**To Reproduce**
1: feedback command
2: click fucked link

**Expected behavior**
The link should work properly

**Additional context**
Fix it bitch

**Comment by noahkra** [comment]
Fixed, twitch keeps periods at the end of the link in the url (discord doesn't). So basically I got rid of the period.
